[tool.poetry]
name = "isra"
version = "2.1.0"
description = "IriusRisk Security Research Assistant: a tool to create components as code"
authors = ["Alvaro Reyes <areyes@iriusrisk.com>"]
readme = "README.md"

[tool.poetry.scripts]
isra = "isra.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.12.3"}
loguru = "^0.7.2"
pytest = "^8.2.0"
beautifulsoup4 = "^4.12.3"
pandas = "^2.2.1"
openpyxl = "^3.1.2"
lxml = "^5.1.0"
keyboard = "^0.13.5"
openai = "^1.25.0"
requests = "^2.32.2"
pyyaml = "^6.0.1"
questionary = "^2.0.1"
rich = "^13.7.1"
importlib-resources = "^6.1.2"
jsonschema = "^4.22.0"
pytest-subtests = "^0.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
